server:
  port: 10000
token:
  signing:
    key: c7f8f904f308cc4c2474df23d4633faac82a9a2c873d1a5835f5444884f42a165cfa15b5038883da071b4de2130f3788160ae171e08d78ea2c5d1c3ae40107bc
spring:
  mail:
    host: <seu host de email>
    port: <a porta>
    username: <email>
    password: <senha>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: <dominio>
  datasource:
    url: jdbc:h2:mem:eu
    username: sa
    password:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create #validate / update/ create / create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        trace: false
        web-allow-others: false
